import paddle.fluid as fluid
f = open("data.proto", "w")
print('name: "MultiSlotDataFeed"', file=f)
print('batch_size: 2', file=f)
print('multi_slot_desc {', file=f)
print('    slots {', file=f)
print('         name: "words"', file=f)
print('         type: "uint64"', file=f)
print('         is_dense: false', file=f)
print('         is_used: true', file=f)
print('     }', file=f)
print('     slots {', file=f)
print('         name: "label"', file=f)
print('         type: "uint64"', file=f)
print('         is_dense: false', file=f)
print('         is_used: true', file=f)
print('    }', file=f)
print('}', file=f)
f.close()
data_feed = fluid.DataFeedDesc('data.proto')
